relay_config:
  name: "Nostr Citadel"
  description: "Nostr Citadel - The Sovereign Relay"
  admin_npub: ""
  admin_email: ""
  relay_url: ""
  behind_proxy: false
  public_relay: false
  dashboard: true
  limits:
    response_event_limit: 2000
sync_config:
  workers: 3
  fetchers: 10
  sync_days_on_init: 7
  sync_whitelisted: false
database:
  name: "citadel.db"