relay_config:
  name: "Nostr Citadel"
  description: "Nostr Citadel - The Sovereign Relay"
  admin_npub: ""
  admin_email: ""
  relay_url: ""
  sync_days_on_init: 7
  behind_proxy: false
  public_relay: false
  dashboard: true
  limits:
    response_event_limit: 2000
importer:
  workers: 3
  fetchers: 10
database:
  name: "citadel.db"
whitelist_config:
  sync_all_whitelisted: false
